### ISSUE TITLE
Error when downloading raw WAV data

### ISSUE THREAD

**Issue by angus-xwu** [lucascesarfd/onc_dataset#3]
Hi Lucas

Thank you for your work on this project.

I was trying to get access to the database as you mentioned in the README file, t but it complains as follow when I trying to download the raw .WAV files

![image](https://github.com/lucascesarfd/onc_dataset/assets/156045481/4737c61d-a95a-4d16-bc5b-b1a99e1f74a8)

Can you help me to resolve this? or if you can give me some hint to fix it?

Many thanks,
Angus

**Comment by psmskelton** [comment]
Is this repeatable? What seems to be happening is ONC is telling us there is a deployment for the hydrophone, but when we query ONC again for the files associated with that deployment, there are no files. I suspect it is caused by the .WAV/.FLAC problem I outlined in https://github.com/lucascesarfd/underwater_snd/issues/3#issuecomment-1886592048. 

You can try changing [lines 131-135](https://github.com/lucascesarfd/onc_dataset/blob/fa81f348efeba02df99f860e94b4639f35b0cc4f/src/download.py#L131C1-L135C6) from:

```python
    available_files = [
        files
        for new_filter in filters
        for files in onc_api.getListByDevice(new_filter, allPages=True)["files"]
    ]
```

To something like (completely untested, not on a dev machine to test it):

```python
for new_filter in filters:
    print(new_filter)
    available_files.extend(onc_api.getListByDevice(new_filter, allPages=True)["files"])
```

This will print the ONC filter that is being sent to getListByDevice().

**Comment by lucascesarfd** [comment]
This issue was solved on the new commit. A try except was included to deal with that.
